name: Build Custom Koha deb

on:
  push:
    branches:
      - apt
jobs:
  build:
    name: Build Custom Docker DEB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print a greeting
      env:
        DOCKERHUB_USERNAME: cmosh
      run: |
        source docker-compose/docker-compose.env