name: Build Custom Koha deb

on:
  push:
    branches:
      - apt
jobs:
  build:
    name: Build Custom Docker DEB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build deb package
      env:
        DOCKERHUB_USERNAME: cmosh
        CI_COMMIT_TAG: "19.11.02"
        KOHA_FORK: cmosh
      run: |
        source docker-compose/docker-compose.env
        if [[ "${CI_COMMIT_TAG}" != "${KOHA_RELEASE}" ]]; then echo "SKIPPED building debian files - uneven tags"; exit 0; fi
        docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml rm -fv koha_patched
        docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml build koha_patched
        docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml up -d --force-recreate --no-deps koha_patched
        docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml logs -f --no-color koha_patched
    - uses: actions/upload-artifact@v1
      with:
        name: koha-patched
        path: koha-patched/debian
    - name: Copy koha-patched to apt folder
      run: |
        cp -r $GITHUB_WORKSPACE/koha-patched/debian .apt/incoming
    - name: Push .deb package
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: .apt/
        GH_PAT: ${{ secrets.GH_PAT }}